```{=html}
<style>
body {
  background-color: #fff5f8;
}

h1, h2, h3 {
  color: #c2185b;
}

.title {
  color: #ad1457;
}

a {
  color: #d81b60;
}
</style>
```

---
title: "Assignment 2"
author: "Emma Rodriguez and Lauren Chetley"
format: html
editor: visual
---

## Quarto
## Loading in the data 
```{r}
library(dataRetrieval)
library(tidyverse)

siteNumbers <- c("14211720", "14211010", "14166000")
parameterCd <- "00010"  # water temperature
startDate <- "2010-01-01"
endDate <- "2023-12-31"

temp_data <- readNWISdv(siteNumbers, parameterCd, startDate, endDate)
```

## Organizing Data 

```{r}
# rename columns for clarity
library(date)
library(lubridate)
library(tidyverse)
colnames(temp_data) <- c("agency_cd", "site_no", "Date", "temp_C")
# extract some date info for use later
temp_data$month = month(temp_data$Date, label=TRUE)
temp_data$year = year(temp_data$Date)

# check by plotting
ggplot(temp_data, aes(x=Date, y=temp_C, color=site_no)) +
  geom_line() +
  labs(title="Stream Temperature at Willamette River Sites",
       x="Date", y="Temperature (°C)", color="Site Number") +
  theme_minimal()

```

## Monthly Summary Data - January

```{r}
#filter for January Temperatures 
library(janitor)
temp_data <- temp_data |>
  clean_names()

jan_data<-temp_data|>
  filter(month=="Jan")

jan_summary <- jan_data |>
  group_by(site_no, year) |>
  summarize(mean_temp = mean(temp_C, na.rm = TRUE), .groups = "drop")

ggplot(jan_data, aes(x = year, y = temp_c, color = site_no)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "lm", se = TRUE) +
  scale_color_manual(values = c(
    "#4CC9F0", 
    "#F72585", 
    "#66FF00"  
  )) +
  labs(title = "January Stream Temperature Trends at Willamette River Sites",
       x = "Year",
       y = "Temperature (°C)",
       color = "Site Number") +
  theme_minimal()
  

#make some summary statistics 
#make a glm - generalized linear model for the data pulled abor 

```
